// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZno5XuBGM5BRErtJuSUzgQzNP4LklK_Q',
    appId: '1:16533015766:web:ec695fc1ee5972502b8d77',
    messagingSenderId: '16533015766',
    projectId: 'orientai-mvp',
    authDomain: 'orientai-mvp.firebaseapp.com',
    storageBucket: 'orientai-mvp.firebasestorage.app',
    measurementId: 'G-ED5SB6RNJS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0lSCUT8VFwkJkzubzmCpqbw55KORfI3U',
    appId: '1:16533015766:android:901854f0f8d8d1bf2b8d77',
    messagingSenderId: '16533015766',
    projectId: 'orientai-mvp',
    storageBucket: 'orientai-mvp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0cfQzm-BU31VMQ3V_jafqZbrzuXfFPbo',
    appId: '1:16533015766:ios:753022b2723e6d992b8d77',
    messagingSenderId: '16533015766',
    projectId: 'orientai-mvp',
    storageBucket: 'orientai-mvp.firebasestorage.app',
    iosBundleId: 'com.example.orientaiMvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0cfQzm-BU31VMQ3V_jafqZbrzuXfFPbo',
    appId: '1:16533015766:ios:753022b2723e6d992b8d77',
    messagingSenderId: '16533015766',
    projectId: 'orientai-mvp',
    storageBucket: 'orientai-mvp.firebasestorage.app',
    iosBundleId: 'com.example.orientaiMvp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZno5XuBGM5BRErtJuSUzgQzNP4LklK_Q',
    appId: '1:16533015766:web:1f59229fd3b79ad52b8d77',
    messagingSenderId: '16533015766',
    projectId: 'orientai-mvp',
    authDomain: 'orientai-mvp.firebaseapp.com',
    storageBucket: 'orientai-mvp.firebasestorage.app',
    measurementId: 'G-12YMD564P6',
  );
}
